# Generated by Django 3.2.16 on 2024-09-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code', models.CharField(max_length=50)),
                ('store_district', models.CharField(max_length=50)),
                ('store_address', models.CharField(max_length=300)),
                ('store_pincode', models.CharField(max_length=10)),
                ('store_contact', models.CharField(max_length=50)),
            ],
        ),
    ]
