# Generated by Django 3.2.16 on 2024-09-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_state',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
