# Generated by Django 5.1.1 on 2024-09-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='stock',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
